cars/urls.py
from django.urls import path
# from rest_framework.permissions import AllowAny

from cars.apps import CarsConfig
from cars.views import (
    StartPage,

    CarsListView,
    CarDetailView,
    CarCreateView,
    CarUpdateView,
    CarDeleteView,

    CategoryList,
    CarsCategoriesListView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
)

app_name = CarsConfig.name

urlpatterns = [
    path("", StartPage.as_view(), name="start-page"),

    path("list/", CarsListView.as_view(), name="cars-list"),
    path("detail/<int:pk>/", CarDetailView.as_view(), name="car-detail"),
    path("create/", CarCreateView.as_view(), name="car-create"),
    path("update/<int:pk>/", CarUpdateView.as_view(), name="car-update"),
    path("delete/<int:pk>/", CarDeleteView.as_view(), name="car-delete"),

    path("category_list/", CategoryList.as_view(), name="category-list"),
    path("cars_categories_list/<int:pk>/", CarsCategoriesListView.as_view(), name="cars-categories-list"),
    path("category_create/", CategoryCreateView.as_view(), name="category-create"),
    path("category_update/<int:pk>/", CategoryUpdateView.as_view(), name="category-update"),
    path("category_delete/<int:pk>/", CategoryDeleteView.as_view(), name="category-delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# from drf_yasg.views import get_schema_view
# from drf_yasg import openapi
# from rest_framework import permissions
#
# schema_view = get_schema_view(
#     openapi.Info(
#         title="Snippets API",
#         default_version="v1",
#         description="Test description",
#         terms_of_service="https://www.google.com/policies/terms/",
#         contact=openapi.Contact(email="contact@snippets.local"),
#         license=openapi.License(name="BSD License"),
#     ),
#     public=True,
#     permission_classes=(permissions.AllowAny,),
# )

urlpatterns = [
    path("admin/", admin.site.urls),

    path("users/", include("users.urls", namespace="users")),
    path("", include("cars.urls", namespace="cars")),

    # path("swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"),
    # path("swagger/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
    # path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
# from rest_framework.permissions import AllowAny
# from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from users.apps import UsersConfig
from users.forms import LoginCustomForm
from users.views import RegisterView, RegisterMessageView, UsersListView, email_verification, UserDetailView, \
    UserDeleteView, UserUpdateView, MessageForUserView

app_name = UsersConfig.name

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path('register_message/', RegisterMessageView.as_view(), name='register-message'),
    path('register/email_confirm/<str:token>/', email_verification, name='email-confirm'),

    path('login/', LoginView.as_view(template_name='users_app/login.html', form_class=LoginCustomForm), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('list/', UsersListView.as_view(), name='users-list'),
    path('detail/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user-update'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='user-delete'),

    path('message/<int:pk>/', MessageForUserView.as_view(), name='user-send-message'),

    # path("token/refresh/", TokenRefreshView.as_view(permission_classes=(AllowAny,)), name="token_refresh"),
    # path("detail/<int:pk>/", UserDetailApiView.as_view(), name="detail"),
    # path("update/<int:pk>/", UserUpdateApiView.as_view(), name="update"),
    # path("delete/<int:pk>/", UserDeleteApiView.as_view(), name="delete"),
    #
    # path("login/", TokenObtainPairView.as_view(permission_classes=(AllowAny,)), name="login"),
    # path("list/", UserListApiView.as_view(), name="list"),
]

cars/models.py
from django.db import models

from users.models import User

NULLABLE = {"blank": True, "null": True}


class Category(models.Model):
    """ Модель Category. """
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='category/', verbose_name='Изображение', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('name',)


class Car(models.Model):
    """ Модель Car. """

    name = models.CharField(max_length=50, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, **NULLABLE, verbose_name="Категория")
    image = models.ImageField(upload_to='car/', verbose_name='Изображение', **NULLABLE)
    year = models.DateField(verbose_name="Год выпуска")
    price = models.PositiveIntegerField(verbose_name='Цена за покупку')
    mileage = models.PositiveIntegerField(verbose_name="Пробег")
    carrying = models.PositiveIntegerField(verbose_name="Грузоподъемность", **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, editable=False, verbose_name='Дата изменения')
    passengers_count = models.PositiveIntegerField(verbose_name="Количество пассажиров без водителя", **NULLABLE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, verbose_name='Владелец')

    def __str__(self):
        return f'Машина: {self.name}, год выпуска: {self.year}'

    class Meta:
        verbose_name = 'Машина'
        verbose_name_plural = 'Машины'

cars/forms.py
from django import forms

from cars.models import Car, Category


class StyleMixin(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            if field_name != 'current_version_indicator' and field_name != 'publication_sign' and field_name != 'is_published':

                field.widget.attrs["class"] = "form-control"  # Применяем ко всем полям, которые не в if


class CarForm(StyleMixin):

    # Список запрещенных слов
    # forbidden_words_list = [
    #     'казино',
    #     'криптовалюта',
    #     'крипта',
    #     'биржа',
    #     'дешево',
    #     'бесплатно',
    #     'обман',
    #     'полиция',
    #     'радар'
    # ]

    class Meta:
        model = Car
        # fields = '__all__'
        fields = ('name', 'description', 'category', 'image', 'year', 'mileage', 'price',)

    # def clean_name(self):
    #     cleaned_data = self.cleaned_data['name']
    #
    #     for word in ProductForm.forbidden_words_list:
    #         if word in cleaned_data.lower():
    #             raise forms.ValidationError('В названии присутствуют недопустимые слова.')
    #     return cleaned_data
    #
    # def clean_description(self):
    #     cleaned_data = self.cleaned_data['description']
    #
    #
    #     for word in ProductForm.forbidden_words_list:
    #         if word in cleaned_data.lower():
    #             raise forms.ValidationError('В описании присутствуют недопустимые слова.')
    #     return cleaned_data


class CategoryForm(StyleMixin):

    class Meta:
        model = Category
        fields = '__all__'
        # fields = ('is_published',)


# class ProductDescriptionForm(StyleMixin):
#
#     class Meta:
#         model = Product
#         # fields = '__all__'
#         fields = ('description',)
#
#
# class ProductCategoryForm(StyleMixin):
#
#     class Meta:
#         model = Product
#         # fields = '__all__'
#         fields = ('category',)
#
#
# class BlogForm(StyleMixin):
#
#     class Meta:
#         model = Blog
#         fields = ('title', 'body', 'preview', 'publication_sign', 'view_count',)
#
#
# class VersionForm(StyleMixin):
#
#     class Meta:
#         model = Version
#         fields = '__all__'

cars/views.py
# from rest_framework.permissions import AllowAny, IsAdminUser, IsAuthenticated
# from rest_framework.response import Response
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from rest_framework.views import APIView
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from cars.forms import CarForm, CategoryForm
# from cars.paginations import CustomPagination
# from cars.serializers import ProductSerializer
from cars.models import Car, Category

# Стартовая страница сайта


class StartPage(TemplateView):
    """ Стартовая страница. """
    template_name = "cars_app/start_page.html"

# CRUD для модели Car


class CarsListView(ListView):
    """ Выводим список машин. """

    model = Car
    template_name = "cars_app/cars_list.html"


class CarDetailView(DetailView):
    """ Выводим выбранную машину. """

    model = Car
    template_name = "cars_app/car_detail.html"


class CarCreateView(LoginRequiredMixin, CreateView):
    """ Создаем машину. """

    model = Car
    template_name = 'cars_app/car_form.html'
    form_class = CarForm
    success_url = reverse_lazy('cars:cars-list')

    def form_valid(self, form):

        car = form.save()
        car.owner = self.request.user
        car.save()

        # context_data = self.get_context_data()
        # formset = context_data['formset']
        #
        # if formset.is_valid():
        #     formset.instance = car
        #     formset.save()
        return super().form_valid(form)


class CarUpdateView(LoginRequiredMixin, UpdateView):
    """ Редактируем выбранную машину. """

    model = Car
    template_name = 'cars_app/car_form.html'
    form_class = CarForm
    success_url = reverse_lazy('cars:cars-list')


class CarDeleteView(LoginRequiredMixin, DeleteView):
    """ Удаляем выбранную машину. """

    model = Car
    template_name = 'cars_app/car_confirm_delete.html'
    success_url = reverse_lazy('cars:cars-list')

# CRUD для модели Category


class CategoryList(ListView):
    """ Выводим список категорий. """

    model = Category
    template_name = "cars_app/category_list.html"


class CarsCategoriesListView(ListView):
    """ Выводим список машин определенной категории. """

    model = Category
    template_name = "cars_app/cars_list_categories.html"

    def get_queryset(self, *args, **kwargs):

        queryset = super().get_queryset(*args, **kwargs)
        id_category = self.kwargs.get("pk")  # Получаем id категории из-под которой заходим

        queryset = queryset.get(pk=id_category)  # Получаем единственную категорию по id

        queryset = queryset.car_set.all()  # Формируем queryset из элементов модели Car с заданной категорией (по id)

        return queryset


class CategoryCreateView(CreateView):
    """ Создаем категорию. """

    model = Category
    template_name = 'cars_app/category_form.html'
    form_class = CategoryForm
    success_url = reverse_lazy('cars:category-list')


class CategoryUpdateView(UpdateView):
    """ Редактируем выбранную категорию. """

    model = Category
    template_name = 'cars_app/category_form.html'
    form_class = CategoryForm
    success_url = reverse_lazy('cars:category-list')


class CategoryDeleteView(DeleteView):
    """ Удаляем выбранную категорию. """

    model = Category
    template_name = 'cars_app/category_confirm_delete.html'
    success_url = reverse_lazy('cars:category-list')

cars/templates/cars_app/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Развалюшка!</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <style>
        .picture {text-align: center;}
        .picture img {width: 80%;}
    </style>
</head>

  <body>

    <div class="container-xxl">



        <br>
        <div class="row text-start">
            <div class="col-sm-9">

                {% include 'cars_app/includes/inc_base.html' %}

            </div>

        </div>
    </div>
<br>
    {% block content %}

    {% endblock %}


        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="container-xxl">
                <br>
                <div class="row">
                    <div class="col-1 col-md">
                        <h3>"Развалюшка!"</h3>
                        <small class="d-block mb-3 text-muted">&copy; 2024</small>
                    </div>
                    <div class="col-6 col-md">
                        <h5><a class="text-muted" href="#">Контакты</a></h5>
                    </div>

                    <div class="col-6 col-md">
                        <h5><a class="text-muted" href="#">Оплата</a></h5>
                    </div>

                    <div class="col-6 col-md">
                        <h5><a class="text-muted" href="#">Доставка</a></h5>
                    </div>

                    <div class="col-6 col-md">
                        <h5><a class="text-muted" href="#">Дополнительно</a></h5>
                    </div>
                </div>
            </div>

        </footer>


    <script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

cars/templates/cars_app/car_confirm_delete.html
{% extends 'cars_app/base.html' %}

{% block content %}

<h1 class="text-center">Автомобильный сервис "Развалюшка"</h1>
<br>

<div class="container">
    <h5 class="text-center">Действительно желаете удалить '{{object.name}}'?</h5>
        <div class="text-center">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <a class="btn btn-light m-3" href="{% url 'cars:car-detail' object.pk %}">Отменить</a>
                <button type="submit" class="btn btn-danger m-3">Да, удалить</button>
            </form>
        </div>
</div>

{% endblock %}

cars/templates/cars_app/car_detail.html
{% extends 'cars_app/base.html' %}

{% load my_tags %}

{% block content %}
<h1 class="text-center">{{object.name}}</h1>
<div class="container">
    <br>
    <div class="row">
        <div class="col-3">

            <div class="card" style="width: 18rem;">
                <div class="card-header">
                    <p class="card-text">{{object.price}}$</p>
                </div>

                <div class="card-body">
                    <img src="{{ object.image|my_media }}" class="card-img-top" alt="...">
                    <a href="{% url 'users:user-detail' object.owner.pk %}" class="btn btn-primary">Связаться с продавцом</a>
                        {% if user.is_superuser %}
                            <a href="#" class="btn btn-primary">Что-то ещё от админа</a>
                        {% endif %}
                </div>

                <div class="card-footer">
                    <p class="card-text"> Владелец: {{object.owner}}</p>
                </div>
            </div>
        </div>
        <div  class="col-6">
            <ul class="list">
                <li><span style="font-size: 20px">{{object.description}}</span></li>
                <li><span style="font-size: 20px">Второй тезис с описанием плюсов или минусов товара.</span></li>
                <li><span style="font-size: 20px">Третий тезис с описанием плюсов или минусов товара.</span></li>
                <li><span style="font-size: 20px">И еще один тезис с описанием плюсов или минусов товара.</span></li>
            </ul>
        </div>
            <div class="col-3">
                {% if user == object.owner or user.is_superuser %}
                     <a class="btn btn-warning m-2" href="{% url 'cars:car-update' object.pk %}">Редактировать</a>
                     <a class="btn btn-danger m-2" href="{% url 'cars:car-delete' object.pk %}">Удалить</a>
                {% endif %}
            </div>

    </div>
</div>
{% endblock %}

cars/templates/cars_app/car_form.html
{% extends 'cars_app/base.html' %}

{% block content %}

<h1 class="text-center">Автомобильный сервис "Развалюшка"</h1>
<br>
    <form method="post" enctype="multipart/form-data">
        <div class="row">

            <div class="col-4">
            </div>

        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        {% if object %}
                            <h3>Редактирование автомобиля</h3>
                        {% else %}
                            <h3>Добавление автомобиля</h3>
                        {% endif %}
                    </div>
                </div>
                <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}

                    {% if object %}
                        <button type="submit" class="btn btn-success">Подтвердить изменения</button>
                    {% else %}
                        <button type="submit" class="btn btn-success">Добавить</button>
                    {% endif %}


                </div>
            </div>
        </div>

            <div class="col-4">
            </div>

        </div>
    </form>

{% endblock %}

cars/templates/cars_app/cars_list.html
{% extends 'cars_app/base.html' %}

{% load my_tags %}

{% block content %}

<h1 class="text-center">Автомобильный сервис "Развалюшка"!</h1>
<div class="container">
    <div class="text-end">
        <a class="btn btn-secondary m-3" href="{% url 'cars:car-create' %}">Добавить</a>
    </div>
    <div class="row">

        {% for object in object_list %}

             <div class="col-3">
                 <br>
                 <div class="card" style="width: 18rem;">
                     <div class="card-header">
                         <h5 class="card-title text-center">{{ object.name }}</h5>
                     </div>

                     <div class="card-body">
                         <img src="{{ object.image|my_media }}" class="card-img-top" alt="...">
                     </div>


                     <div class="card-footer">
                         <p class="card-text">{{ object.price }}$</p>
                         <a href="{% url 'cars:car-detail' object.pk %}" class="btn btn-primary">Подробнее</a>
                     </div>

                 </div>

             </div>

        {% endfor %}
    </div>

</div>

{% endblock %}

cars/templates/cars_app/cars_list_categories.html
{% extends 'cars_app/base.html' %}

{% load my_tags %}

{% block content %}

<h1 class="text-center">Автомобильный сервис "Развалюшка"!</h1>
<div class="container">
<!--    <div class="text-end">-->
<!--        <a class="btn btn-secondary m-3" href="#">Добавить</a>-->
<!--    </div>-->
    <div class="row">
        {% for object in object_list %}

                 <div class="col-3">

                     <div class="card" style="width: 18rem;">

                         <div class="card-header">
                             <h5 class="card-title text-center">{{ object.name }}</h5>
                         </div>

                         <div class="card-body">
                             <img src="{{ object.image|my_media }}" class="card-img-top" alt="...">
                         </div>


                         <div class="card-footer">
                             <p class="card-text">{{ object.price }}$</p>
                             <a href="{% url 'cars:car-detail' object.pk %}" class="btn btn-primary">Подробнее</a>
                         </div>

                     </div>

                 </div>

        {% endfor %}
    </div>

</div>

{% endblock %}

cars/templates/cars_app/category-list.html
{% extends 'cars_app/base.html' %}

{% load my_tags %}

{% block content %}

<h1 class="text-center">Автомобильный сервис "Развалюшка"!</h1>
<div class="container">
    <div class="text-end">
        <a class="btn btn-secondary m-3" href="#">Добавить</a>
    </div>
    <div class="row">

        {% for object in object_list %}

             <div class="col-3">

                 <div class="card" style="width: 18rem;">

                     <div class="card-header">
                         <h5 class="card-title text-center">{{ object.name }}</h5>
                     </div>

                     <div class="card-body">
                         <img src="{{ object.image|my_media }}" class="card-img-top" alt="...">
                     </div>


                     <div class="card-body">
                         <p class="card-text">{{ object.description }}</p>
                         <a href="#" class="btn btn-primary">Подробнее</a>
                     </div>

                     <div class="card-footer">
                     </div>

                 </div>

             </div>

        {% endfor %}
    </div>

</div>

{% endblock %}

cars/templates/cars_app/category_confirm_delete.html
{% extends 'cars_app/base.html' %}

{% block content %}

<h1 class="text-center">Автомобильный сервис "Развалюшка"</h1>
<br>

<div class="container">
    <h5 class="text-center">Действительно желаете удалить категорию '{{object.name}}'?</h5>
        <div class="text-center">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <a class="btn btn-light m-3" href="{% url 'cars:car-detail' object.pk %}">Отменить</a>
                <button type="submit" class="btn btn-danger m-3">Да, удалить</button>
            </form>
        </div>
</div>

{% endblock %}

cars/templates/cars_app/category_form.html
{% extends 'cars_app/base.html' %}

{% block content %}

<h1 class="text-center">Автомобильный сервис "Развалюшка"</h1>
<br>
    <form method="post" enctype="multipart/form-data">
        <div class="row">

            <div class="col-4">
            </div>

        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        {% if object %}
                            <h3>Редактирование категории</h3>
                        {% else %}
                            <h3>Добавление категории</h3>
                        {% endif %}
                    </div>
                </div>
                <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}

                    {% if object %}
                        <button type="submit" class="btn btn-success">Подтвердить изменения</button>
                    {% else %}
                        <button type="submit" class="btn btn-success">Добавить</button>
                    {% endif %}


                </div>
            </div>
        </div>

            <div class="col-4">
            </div>

        </div>
    </form>

{% endblock %}

cars/templates/cars_app/category_list.html
{% extends 'cars_app/base.html' %}

{% load my_tags %}

{% block content %}

<h1 class="text-center">Автомобильный сервис "Развалюшка"!</h1>
<div class="container">
    <div class="text-end">
        {% if user.is_superuser %}
            <a class="btn btn-secondary m-3" href=" {% url 'cars:category-create' %}">Добавить категорию</a>
        {% endif %}
    </div>
    <div class="row">

        {% for object in object_list %}

             <div class="col-3">

                 <div class="card" style="width: 18rem;">

                     <div class="card-header">
                         <h5 class="card-title text-center">{{ object.name }}</h5>
                     </div>

                     <div class="card-body">
                         <img src="{{ object.image|my_media }}" class="card-img-top" alt="...">
                     </div>


                     <div class="card-body">
                         <p class="card-text">{{ object.description }}</p>
                         <a href="{% url 'cars:cars-categories-list' object.pk %}" class="btn btn-primary">Подробнее</a>
                         {% if user.is_superuser %}
                             <a href="{% url 'cars:category-update' object.pk %}" class="btn btn-warning">Редактировать</a>
                             <p></p>
                             <p class="card-text text-center">
                                 <a href="{% url 'cars:category-delete' object.pk %}" class="btn btn-danger">Удалить</a>
                             </p>
                         {% endif %}
                     </div>

                     <div class="card-footer">
                     </div>

                 </div>

             </div>

        {% endfor %}
    </div>

</div>

{% endblock %}

cars/templates/cars_app/start-page.html
{% extends 'cars_app/base.html' %}

{% block content %}

<h1 style="text-align: center; font-size: 32pt;">Добро пожаловать на автомобильный сервис <em>"Развалюшка"</em>!</h1>
    <br>
    <h4 style="text-align: center; font-size: 18pt;">
        Здесь, Вы, можете купить или продать подержаный автомобиль, а также просто узнать "чо-почём"
    </h4>
    <br>
    <p class="picture"><img src="media/car/collage.jpg" title="Машинки"></p>
    <address class="text-end">Наш адрес: ул.Хорошая, д.11</address>

{% endblock %}

cars/templates/cars_app/start_page.html
{% extends 'cars_app/base.html' %}

{% block content %}

<h1 style="text-align: center; font-size: 32pt;">Добро пожаловать на автомобильный сервис <em>"Развалюшка"</em>!</h1>
    <br>
    <h4 style="text-align: center; font-size: 18pt;">
        Здесь, Вы, можете купить или продать подержаный автомобиль, а также просто узнать "чо-почём"
    </h4>
    <br>
    <p class="picture"><img src="media/car/collage.jpg" title="Машинки"></p>
    <address class="text-end">Наш адрес: ул.Хорошая, д.11</address>

{% endblock %}