cars/urls.py
from django.urls import path
# from rest_framework.permissions import AllowAny

from cars.apps import CarsConfig
from cars.views import (
    StartPage,

    CarsListView,
    CarDetailView,
    CarCreateView,
    CarUpdateView,
    CarDeleteView,

    CategoryList,
    CarsCategoriesListView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
)

app_name = CarsConfig.name

urlpatterns = [
    path("", StartPage.as_view(), name="start-page"),

    path("list/", CarsListView.as_view(), name="cars-list"),
    path("detail/<int:pk>/", CarDetailView.as_view(), name="car-detail"),
    path("create/", CarCreateView.as_view(), name="car-create"),
    path("update/<int:pk>/", CarUpdateView.as_view(), name="car-update"),
    path("delete/<int:pk>/", CarDeleteView.as_view(), name="car-delete"),

    path("category_list/", CategoryList.as_view(), name="category-list"),
    path("cars_categories_list/<int:pk>/", CarsCategoriesListView.as_view(), name="cars-categories-list"),
    path("category_create/", CategoryCreateView.as_view(), name="category-create"),
    path("category_update/<int:pk>/", CategoryUpdateView.as_view(), name="category-update"),
    path("category_delete/<int:pk>/", CategoryDeleteView.as_view(), name="category-delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# from drf_yasg.views import get_schema_view
# from drf_yasg import openapi
# from rest_framework import permissions
#
# schema_view = get_schema_view(
#     openapi.Info(
#         title="Snippets API",
#         default_version="v1",
#         description="Test description",
#         terms_of_service="https://www.google.com/policies/terms/",
#         contact=openapi.Contact(email="contact@snippets.local"),
#         license=openapi.License(name="BSD License"),
#     ),
#     public=True,
#     permission_classes=(permissions.AllowAny,),
# )

urlpatterns = [
    path("admin/", admin.site.urls),

    path("users/", include("users.urls", namespace="users")),
    path("", include("cars.urls", namespace="cars")),

    # path("swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"),
    # path("swagger/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
    # path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
# from rest_framework.permissions import AllowAny
# from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from users.apps import UsersConfig
from users.forms import LoginCustomForm
from users.views import RegisterView, RegisterMessageView, UsersListView, email_verification, UserDetailView, \
    UserDeleteView, UserUpdateView, MessageForUserView

app_name = UsersConfig.name

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path('register_message/', RegisterMessageView.as_view(), name='register-message'),
    path('register/email_confirm/<str:token>/', email_verification, name='email-confirm'),

    path('login/', LoginView.as_view(template_name='users_app/login.html', form_class=LoginCustomForm), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('list/', UsersListView.as_view(), name='users-list'),
    path('detail/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user-update'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='user-delete'),

    path('message/<int:pk>/', MessageForUserView.as_view(), name='user-send-message'),

    # path("token/refresh/", TokenRefreshView.as_view(permission_classes=(AllowAny,)), name="token_refresh"),
    # path("detail/<int:pk>/", UserDetailApiView.as_view(), name="detail"),
    # path("update/<int:pk>/", UserUpdateApiView.as_view(), name="update"),
    # path("delete/<int:pk>/", UserDeleteApiView.as_view(), name="delete"),
    #
    # path("login/", TokenObtainPairView.as_view(permission_classes=(AllowAny,)), name="login"),
    # path("list/", UserListApiView.as_view(), name="list"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name="Почта")
    phone = models.CharField(max_length=50, verbose_name="Телефон", **NULLABLE)
    city = models.CharField(max_length=50, verbose_name="Город", **NULLABLE)
    avatar = models.ImageField(upload_to="users/avatars", verbose_name="Аватар", **NULLABLE)
    token = models.CharField(max_length=100, verbose_name="Сгенерированный пароль", **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return f"{self.email}"


class Message(models.Model):
    addressee = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Получатель", **NULLABLE)
    message = models.TextField(verbose_name="Сообщение", **NULLABLE)

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"

    def __str__(self):
        return f"{self.message}"

users/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from users.models import User, Message


class StyleMixin(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            if field_name != "is_superuser" and field_name != "is_staff" and field_name != "is_active":
                field.widget.attrs["class"] = "form-control"


class RegisterForm(StyleMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class LoginCustomForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

# class UserRegisterForm(StyleMixin, UserCreationForm):
#
#     class Meta:
#         model = User
#         fields = ('email', 'password1', 'password2',)
#
#
# class PasswordRecoveryForm(StyleMixin, forms.ModelForm):
#
#     class Meta:
#         model = User
#         fields = ('email',)


class UserForm(StyleMixin):
    class Meta:
        model = User
        # fields = '__all__'
        fields = ("email", "city", "phone", "avatar", "is_superuser", "is_staff", "is_active")


class MessageForm(StyleMixin):
    class Meta:
        model = Message
        fields = ("message",)

users/views.py
import random

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, ListView, UpdateView, DetailView, DeleteView

# from rest_framework.generics import (
#     CreateAPIView,
#     DestroyAPIView,
#     ListAPIView,
#     RetrieveAPIView,
#     UpdateAPIView,
# )
# from rest_framework.permissions import AllowAny, IsAdminUser, IsAuthenticated
# from rest_framework.response import Response
# from rest_framework.views import APIView

from config import settings
from config.settings import EMAIL_HOST_USER
from users.forms import RegisterForm, UserForm, MessageForm
from users.models import User, Message


# from users.paginations import CustomPagination
# from users.serializers import UserSerializer


class RegisterView(CreateView):
    """ Регистрируем пользователя. """

    model = User
    template_name = 'users_app/user_form.html'
    form_class = RegisterForm
    success_url = reverse_lazy('users:register-message')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False

        token = "".join([str(random.randint(0, 9)) for i in range(10)])
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/register/email_confirm/{token}/'
        send_mail(
            'Подтверждение почты',
            f'Перейдите по ссылке для подтверждения почты {url}',
            EMAIL_HOST_USER,
            [user.email],
        )
        return super().form_valid(form)


class RegisterMessageView(TemplateView):

    template_name = 'users_app/register_message.html'


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    # return redirect(reverse('users:login'))
    return HttpResponseRedirect('/users/login/')


class UsersListView(UserPassesTestMixin, ListView):

    model = User
    template_name = 'users_app/users_list.html'

    def test_func(self):
        user =self.request.user
        return user.is_superuser


class UserDetailView(DetailView):

    model = User
    template_name = 'users_app/user_detail.html'


class UserUpdateView(UserPassesTestMixin, UpdateView):

    model = User
    template_name = 'users_app/user_form.html'
    form_class = UserForm
    success_url = reverse_lazy('users:users-list')

    def test_func(self):
        user =self.request.user
        return user.is_superuser


class UserDeleteView(UserPassesTestMixin, DeleteView):

    model = User
    template_name = 'users_app/user_confirm_delete.html'
    success_url = reverse_lazy('users:users-list')

    def test_func(self):
        user =self.request.user
        return user.is_superuser


class MessageForUserView(CreateView):
    """ Отправляем сообщение пользователю. """

    model = User
    form_class = MessageForm
    template_name = 'users_app/send_message_form.html'
    success_url = reverse_lazy('users:users-list')
    
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data()
    #     context['email_for_send'] = self.request.user.email
    #     return context

    # def get_queryset(self, *args, **kwargs):
    #     queryset = super().get_queryset(*args, **kwargs)
    #
    #     id_addressee = self.kwargs.get("pk")
    #
    #     return queryset

    def form_valid(self, form):
        message = form.save()
        # message = form.save()
        addressee = message.addressee
        # email_for_send = User.objects.get(pk=user_id).email
        # text = user.message_set.get(pk=1)
        # user.save()
        #
        # send_mail(
        #     'Сообщение от Admin',
        #     f'{text}',
        #     EMAIL_HOST_USER,
        #     [email_for_send],
        # )
        # print(f'адрес: {email_for_send}')
        # print(f'id: {user_id}')
        print("Привет!")
        print(f'addressee: {addressee}')
        return super().form_valid(form)
    #
    # def messages_delete(request):
    #     """ Удаляем все сообщения пользователю. """
    #
    #     messages = Message.objects.all()
    #     messages.delete()

users/templates/users_app/login.html
{% extends 'cars_app/base.html' %}

{% block content %}
<h1 class="text-center">Автомобильный сервис "Развалюшка"</h1>
<br>
    <form method="post" enctype="multipart/form-data">
        <div class="row">

            <div class="col-4">
            </div>

            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">

                        </div>
                    </div>
                    <div class="card-body">

                        {% csrf_token %}
                        {{ form.as_p }}

                        <button type="submit" class="btn btn-success">Войти</button>
                        <a class="p-l-2 btn btn-primary" href="#">Забыли пароль?</a>

                    </div>
                </div>
            </div>

            <div class="col-4">
            </div>

        </div>
    </form>

{% endblock %}

users/templates/users_app/password_recovery_form.html
{% extends 'cars_app/base.html' %}

{% block content %}
<h1 class="text-center">Автомобильный сервис "Развалюшка"</h1>
<br>
    <form method="post" enctype="multipart/form-data">
        <div class="row">

            <div class="col-3">
            </div>

            <div class="col-6">
                <div class="card">
                    <div class="card-header text-center">
                        <div class="card-title">
                            <h5>Введите адрес электронной почты и вам будет выслан новый пароль</h5>
                        </div>
                    </div>

                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            {% csrf_token %}
                            <label class="form-label">Email</label>
                            <input type="email" name="email" class="form-control">

                            <button type="submit" class="btn btn-primary m-3">Отправить</button>
                        </form>

                    </div>
                </div>
            </div>

        </div>
    </form>

{% endblock %}

users/templates/users_app/password_recovery_message.html
{% extends 'cars_app/base.html' %}

{% load my_tags %}

{% block content %}
<div class="container">
    <br>
    <div class="row text-center">
        <h4>На указанную почту отправлено сообщение с новым паролем</h4>
    </div>
</div>
{% endblock %}

users/templates/users_app/register_message.html
{% extends 'cars_app/base.html' %}

{% load my_tags %}

{% block content %}
<div class="container">
    <br>
    <div class="row text-center">
        <h4>На указанную почту отправлено сообщение.</h4>
    </div>
</div>
{% endblock %}

users/templates/users_app/send_message_form.html
{% extends 'cars_app/base.html' %}

{% block content %}
<h1 class="text-center">Автомобильный сервис "Развалюшка"</h1>
<br>
    <form method="post" enctype="multipart/form-data">
        <div class="row">

            <div class="col-4">
            </div>

            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <h4>Сообщение для пользователя: {{object.email}}</h4>
                        </div>
                    </div>
                    <div class="card-body">

                        {% csrf_token %}
                        {{ form.as_p }}

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-success">Отправить</button>
                    </div>
                </div>
            </div>

            <div class="col-4">
            </div>

        </div>
    </form>

{% endblock %}

users/templates/users_app/user_confirm_delete.html
{% extends 'cars_app/base.html' %}

{% block content %}

<h1 class="text-center">Автомобильный сервис "Развалюшка"</h1>
<br>

<div class="container">
    <h5 class="text-center">Действительно желаете удалить '{{object.email}}'?</h5>
        <div class="text-center">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <a class="btn btn-primary m-3" href="{% url 'users:user-detail' object.pk %}">Отменить</a>
                <button type="submit" class="btn btn-danger m-3">Да, удалить</button>
            </form>
        </div>
</div>

{% endblock %}

users/templates/users_app/user_detail.html
{% extends 'cars_app/base.html' %}

{% load my_tags %}

{% block content %}

<div class="container-fluid">
    <br>
    <div class="row">
        <div class="col-1">
        </div>

        <div class="col-4">

            <div class="card w-100" style="width: 18rem;">
                <div class="card-header  text-center">
                    <p class="card-text">
                        <h4>Пользователь: {{object.email}}</h4>
                    </p>
                </div>

                <div class="card-body text-center">
                    <img src="{{ object.avatar|my_media }}" class="card-img-top" alt="...">

                </div>

                <div class="card-footer text-center">
                    {% if user.is_authenticated %}
                        <p>
                            <a href="{% url 'users:user-update' object.pk %}" class="btn btn-primary">Внести изменения</a>
                            <a href="{% url 'users:user-delete' object.pk %}" class="btn btn-danger">Удалить</a>
                        </p>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="col-5">

            <p class="card-text">
                <h4>Город: {{object.city}}</h4>
            </p>
            <p class="card-text">
                <h4>Телефон: {{object.phone}}</h4>
            </p>
            <p class="card-text">
                <h4>Почта: {{object.email}}</h4>
            </p>



        </div>

        <div class="col-2">
            {% if user.is_authenticated %}
                <a href="{% url 'users:user-send-message' object.pk %}" class="btn btn-primary">Отправить сообщение</a>
            {% endif %}
        </div>

    </div>
</div>
{% endblock %}

users/templates/users_app/user_form.html
{% extends 'cars_app/base.html' %}

{% block content %}
<h1 class="text-center">Автомобильный сервис "Развалюшка"</h1>
<br>
    <form method="post" enctype="multipart/form-data">
        <div class="row">

            <div class="col-4">
            </div>

            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            {% if not user.is_authenticated %}
                                <h4>Регистрация пользователя</h4>
                            {% else %}
                                <h4>Редактирование данных пользователя</h4>
                            {% endif %}
                        </div>
                    </div>
                    <div class="card-body">

                        {% csrf_token %}
                        {{ form.as_p }}
                        {% if user %}
                            <button type="submit" class="btn btn-success">Подтвердить изменения</button>
                        {% else %}
                            <button type="submit" class="btn btn-success">Зарегистрироваться</button>
                        {% endif %}


                    </div>
                </div>
            </div>

            <div class="col-4">
            </div>

        </div>
    </form>

{% endblock %}

users/templates/users_app/users_list.html
{% extends 'cars_app/base.html' %}

{% load my_tags %}

{% block content %}

<h1 class="text-center">Автомобильный сервис "Развалюшка"!</h1>
<br>
<br>
<h2 class="text-center">Наши пользователи</h2>

<div class="container">

    <div class="row">

        {% for object in object_list %}

             <div class="col-3">
                 <br>
                 <div class="card" style="width: 18rem;">
                     <div class="card-header">
                         <h5 class="card-title text-center">{{ object.email }}</h5>
                     </div>

                     <div class="card-body">
                         <p>
                            <img src="{{ object.avatar|my_media }}" class="card-img-top" alt="...">
                         </p>

                         {% if object.is_active %}
                            <p>Активен</p>
                         {% else %}
                            <p>Неактивен</p>
                         {% endif %}

                     </div>


                     <div class="card-footer">
                         <a href="{% url 'users:user-detail' object.pk %}" class="btn btn-primary">Подробнее</a>
                     </div>

                 </div>

             </div>

        {% endfor %}
    </div>

</div>

{% endblock %}